name: locales-launch
summary: Fix Glibc locales support and GNU Gettext I18N
description: >
  This remote part ships the `locales-launch` launcher to your snap, this launcher fixes Glibc locales support and allows GNU Gettext-based internationalization(I18N) to work.

  Refer the following snapcraft forum topic for more information regarding using this remote part:
  _TITLE_
  _URL_

version: current

grade: stable
confinement: strict

parts:
  locales-launch:
    plugin: dump
    source: launchers
    organize:
      '*': bin/
    stage-packages:
    # For localedef(1)
    - libc-bin

    # For locale data used by localedef(1)
    - locales

    # All pre-generated locale data
    # DISABLED: Lots of duplicate data will be included in snap when this is staged, unless the target machine has no resource to generate them in runtime otherwise not using it
    #
    #   Lack of compiled locales breaks gettext based localisation - snapcraft - snapcraft.io
    #   https://forum.snapcraft.io/t/lack-of-compiled-locales-breaks-gettext-based-localisation/3758
    #
    #- locales-all
